fixtures:
  repositories:
    archive:
      repo: "https://github.com/camptocamp/puppet-archive.git"
      ref: "0.8.1"
    composer:
      repo: "https://github.com/willdurand/puppet-composer.git"
      ref: "1.2.10"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "v9.0.2"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "v9.4.1"
    # provided by puppet-agent
    augeas:
      repo: "https://github.com/puppetlabs/puppetlabs-augeas_core"
      ref: "v1.2.0"
    cron:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      ref: "v1.2.0"
  symlinks:
    roundcube: "#{source_dir}"

