name 'tohuwabohu-roundcube'
version '1.3.2'
source 'https://github.com/tohuwabohu/puppet-roundcube.git'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Install and manage the Roundcube web-based email client'
project_page 'https://github.com/tohuwabohu/puppet-roundcube'
description ''
dependency 'puppetlabs/stdlib', '4.x'
dependency 'camptocamp/archive', '0.x'
dependency 'ripienaar/module_data', '0.0.x'
