name 'tohuwabohu-roundcube'
version '1.3.2'
source 'https://github.com/tohuwabohu/puppet-roundcube.git'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Install and manage the Roundcube web-based email client'
project_page 'https://github.com/tohuwabohu/puppet-roundcube'
description ''

dependency 'example42/puppi', '2.x'
dependency 'puppetlabs/stdlib', '4.x'
dependency 'gini/archive', '0.2.x'
