name    'MartinMeinhold-roundcube'
version '1.1.0'
source 'git@bitbucket.org:MartinMeinhold/puppet-module-roundcube.git'
author 'MartinMeinhold'
license 'Apache License, Version 2.0'
summary 'Install and manage the Roundcube webmail application'
description ''
project_page 'https://bitbucket.org/MartinMeinhold/puppet-module-roundcube'

dependency 'example42/puppi', '2.x'
dependency 'puppetlabs/stdlib', '4.x'
dependency 'gini/archive', '0.2.x'
dependency 'puppetlabs/postgresql', '2.x'
